<a href="https://colab.research.google.com/github/sap-tarshi-ghosh/python_/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
!pip install numpy

In [43]:
import numpy as np

In [4]:
print(np.__version__)

2.0.2


In [47]:
#creating a numpy 1-d array with np alias
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

#typre of numpy array
print(type(arr1))

[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [28]:
#2-d array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [20]:
#3-d array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [29]:
print(f'dimension of arr1: {arr1.ndim}d')
print(f'dimension of arr1: {arr2.ndim}d')
print(f'dimension of arr1: {arr3.ndim}d')

dimension of arr1: 1d
dimension of arr1: 2d
dimension of arr1: 3d


In [21]:
arr3.size

12

In [35]:
# acessing array elements
print(arr2[0][1]+arr2[1,2] + arr3[1,1,2] + arr3[0][1][1])

19


In [40]:
#negative indexing
print('last element of arr3: ', arr3[-1])

last element of arr3:  [[1 2 3]
 [4 5 6]]


# Array creation functions

In [51]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [56]:
np.linspace(0, 1, 3) #add equal scacingin defined range

array([0. , 0.5, 1. ])

# Slicing basics

In [26]:
arr1[1:3]

array([2, 3])

In [60]:
#column selection
arr2[:,1]

array([2, 5])

# Array operation

In [31]:
arr1

array([1, 2, 3, 4, 5])

In [61]:
temp = arr1 * 5
print(temp)

[ 5 10 15 20 25]


In [36]:
a =  arr1 + 7
b = arr1 * 2
a + b

array([10, 13, 16, 19, 22])

Mathematical functions

In [68]:
temp = np.sum(arr1)
temp = np.mean(arr1)
temp = np.std(arr1)
temp = np.median(arr1)
temp = np.min(arr1)
temp = np.max(arr1)
temp

np.int64(5)

# Reshape

In [40]:
arr = np.arange(1,10)

arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])